ENABLE_EMAIL_NOTIFICATIONS=false
INVITATION_VIA_EMAIL=false
SMTP_PWD=none
SMTP_USER=none
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
DB_URL=localhost:5432/atlas
DB_USER=postgres
DB_PWD=admin
POSTGRES_USER=rootUser
POSTGRES_PWD=mypassword
JWT_SECRET_KEY=your_jwt_secret
ALLOWED_ORGANIZATION_ADMINS=
GOOGLE_KEY=
GOOGLE_TRACKING_ID=
PUBLIC_FRONT_URL=http://localhost:3000
PUBLIC_API_URL=http://localhost:8080
GCP_BUCKET_NAME=
GCP_JSON=
GCP_PROJECT_ID=
MINIO_USER=minioadmin
MINIO_PASSWORD=minioadmin
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
PUBLIC_MINIO_ENDPOINT=http://localhost:9000
MINIO_ENDPOINT=http://localhost:9000
STORAGE_TYPE=MINIO
MINIO_BUCKET=atlas-test
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
MAIL_RECIPIENTS=
STORAGE_TYPE=MINIO
LICENSE_KEY=
ENABLE_SSO=false
OAUTH2_PROVIDER=
OAUTH2_CLIENT_ID=
OAUTH2_CLIENT_SECRET=
MUI_X_LICENSE=
LICENSE_FINGERPRINT_REQUIRED=true
LOGO_PATHS=
CUSTOM_COLORS=
BRAND_CONFIG=
FASTSPRING_USER=
FASTSPRING_PWD=